// Map of country codes / common short names to flag emojis.
// Accepts FIFA 3-letter codes, ISO-3, ISO-2, or full team names.
const FLAGS: Record<string, string> = {
  ESP: "🇪🇸", SPA: "🇪🇸", SP: "🇪🇸",
  BRA: "🇧🇷", BR: "🇧🇷",
  ARG: "🇦🇷", AR: "🇦🇷",
  FRA: "🇫🇷", FR: "🇫🇷",
  GER: "🇩🇪", DEU: "🇩🇪", DE: "🇩🇪",
  ITA: "🇮🇹", IT: "🇮🇹",
  POR: "🇵🇹", PT: "🇵🇹",
  ENG: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", GBR: "🇬🇧", UK: "🇬🇧",
  NED: "🇳🇱", NL: "🇳🇱", HOL: "🇳🇱",
  BEL: "🇧🇪", BE: "🇧🇪",
  CRO: "🇭🇷", HR: "🇭🇷",
  URU: "🇺🇾", UY: "🇺🇾",
  COL: "🇨🇴", CO: "🇨🇴",
  MEX: "🇲🇽", MX: "🇲🇽",
  USA: "🇺🇸", US: "🇺🇸",
  CAN: "🇨🇦", CA: "🇨🇦",
  JPN: "🇯🇵", JP: "🇯🇵",
  KOR: "🇰🇷", KR: "🇰🇷",
  AUS: "🇦🇺", AU: "🇦🇺",
  MAR: "🇲🇦", MA: "🇲🇦",
  SEN: "🇸🇳", SN: "🇸🇳",
  GHA: "🇬🇭", GH: "🇬🇭",
  NGA: "🇳🇬", NG: "🇳🇬",
  CMR: "🇨🇲", CM: "🇨🇲",
  EGY: "🇪🇬", EG: "🇪🇬",
  ALG: "🇩🇿", DZA: "🇩🇿",
  TUN: "🇹🇳", TN: "🇹🇳",
  SUI: "🇨🇭", CH: "🇨🇭",
  POL: "🇵🇱", PL: "🇵🇱",
  DEN: "🇩🇰", DK: "🇩🇰",
  SWE: "🇸🇪", SE: "🇸🇪",
  NOR: "🇳🇴", NO: "🇳🇴",
  SRB: "🇷🇸", RS: "🇷🇸",
  SUI2: "🇨🇭",
  WAL: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  SCO: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  IRL: "🇮🇪", IE: "🇮🇪",
  TUR: "🇹🇷", TR: "🇹🇷",
  RUS: "🇷🇺", RU: "🇷🇺",
  UKR: "🇺🇦", UA: "🇺🇦",
  CHI: "🇨🇱", CL: "🇨🇱",
  PER: "🇵🇪", PE: "🇵🇪",
  ECU: "🇪🇨", EC: "🇪🇨",
  PAR: "🇵🇾", PY: "🇵🇾",
  BOL: "🇧🇴", BO: "🇧🇴",
  VEN: "🇻🇪", VE: "🇻🇪",
  CRC: "🇨🇷", CR: "🇨🇷",
  PAN: "🇵🇦", PA: "🇵🇦",
  HON: "🇭🇳", HN: "🇭🇳",
  JAM: "🇯🇲", JM: "🇯🇲",
  KSA: "🇸🇦", SAU: "🇸🇦", SA: "🇸🇦",
  IRN: "🇮🇷", IR: "🇮🇷",
  IRQ: "🇮🇶", IQ: "🇮🇶",
  QAT: "🇶🇦", QA: "🇶🇦",
  UAE: "🇦🇪", AE: "🇦🇪",
  CHN: "🇨🇳", CN: "🇨🇳",
};

const NAME_TO_FLAG: Record<string, string> = {
  españa: "🇪🇸", espana: "🇪🇸", spain: "🇪🇸",
  brasil: "🇧🇷", brazil: "🇧🇷",
  argentina: "🇦🇷",
  francia: "🇫🇷", france: "🇫🇷",
  alemania: "🇩🇪", germany: "🇩🇪",
  italia: "🇮🇹", italy: "🇮🇹",
  portugal: "🇵🇹",
  inglaterra: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "países bajos": "🇳🇱", "paises bajos": "🇳🇱", holanda: "🇳🇱", netherlands: "🇳🇱",
  bélgica: "🇧🇪", belgica: "🇧🇪", belgium: "🇧🇪",
  croacia: "🇭🇷", croatia: "🇭🇷",
  uruguay: "🇺🇾",
  colombia: "🇨🇴",
  méxico: "🇲🇽", mexico: "🇲🇽",
  "estados unidos": "🇺🇸", "united states": "🇺🇸", usa: "🇺🇸",
  canadá: "🇨🇦", canada: "🇨🇦",
  japón: "🇯🇵", japon: "🇯🇵", japan: "🇯🇵",
  "corea del sur": "🇰🇷", "south korea": "🇰🇷",
  australia: "🇦🇺",
  marruecos: "🇲🇦", morocco: "🇲🇦",
  senegal: "🇸🇳",
  ghana: "🇬🇭",
  nigeria: "🇳🇬",
  camerún: "🇨🇲", camerun: "🇨🇲", cameroon: "🇨🇲",
  egipto: "🇪🇬", egypt: "🇪🇬",
  suiza: "🇨🇭", switzerland: "🇨🇭",
  polonia: "🇵🇱", poland: "🇵🇱",
  dinamarca: "🇩🇰", denmark: "🇩🇰",
  suecia: "🇸🇪", sweden: "🇸🇪",
  noruega: "🇳🇴", norway: "🇳🇴",
  serbia: "🇷🇸",
  gales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  escocia: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  irlanda: "🇮🇪", ireland: "🇮🇪",
  turquía: "🇹🇷", turquia: "🇹🇷", turkey: "🇹🇷",
  rusia: "🇷🇺", russia: "🇷🇺",
  ucrania: "🇺🇦", ukraine: "🇺🇦",
  chile: "🇨🇱",
  perú: "🇵🇪", peru: "🇵🇪",
  ecuador: "🇪🇨",
  paraguay: "🇵🇾",
  bolivia: "🇧🇴",
  venezuela: "🇻🇪",
  "costa rica": "🇨🇷",
  panamá: "🇵🇦", panama: "🇵🇦",
  honduras: "🇭🇳",
  jamaica: "🇯🇲",
  "arabia saudí": "🇸🇦", "arabia saudita": "🇸🇦", "saudi arabia": "🇸🇦",
  irán: "🇮🇷", iran: "🇮🇷",
  irak: "🇮🇶", iraq: "🇮🇶",
  catar: "🇶🇦", qatar: "🇶🇦",
  "emiratos árabes unidos": "🇦🇪", "united arab emirates": "🇦🇪",
  china: "🇨🇳",
};

export function flagFor(short?: string, name?: string): string | null {
  if (short) {
    const f = FLAGS[short.toUpperCase()];
    if (f) return f;
  }
  if (name) {
    const f = NAME_TO_FLAG[name.trim().toLowerCase()];
    if (f) return f;
  }
  return null;
}
