/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as BetsRouteImport } from './routes/bets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaguesIndexRouteImport } from './routes/leagues.index'
import { Route as LeaguesLeagueIdRouteImport } from './routes/leagues.$leagueId'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as ApiPublicCronSyncMatchesRouteImport } from './routes/api/public/cron/sync-matches'
import { Route as ApiPublicCronResolveBetsRouteImport } from './routes/api/public/cron/resolve-bets'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BetsRoute = BetsRouteImport.update({
  id: '/bets',
  path: '/bets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesIndexRoute = LeaguesIndexRouteImport.update({
  id: '/leagues/',
  path: '/leagues/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesLeagueIdRoute = LeaguesLeagueIdRouteImport.update({
  id: '/leagues/$leagueId',
  path: '/leagues/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSyncMatchesRoute =
  ApiPublicCronSyncMatchesRouteImport.update({
    id: '/api/public/cron/sync-matches',
    path: '/api/public/cron/sync-matches',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronResolveBetsRoute =
  ApiPublicCronResolveBetsRouteImport.update({
    id: '/api/public/cron/resolve-bets',
    path: '/api/public/cron/resolve-bets',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bets': typeof BetsRoute
  '/profile': typeof ProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/api/public/cron/resolve-bets': typeof ApiPublicCronResolveBetsRoute
  '/api/public/cron/sync-matches': typeof ApiPublicCronSyncMatchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bets': typeof BetsRoute
  '/profile': typeof ProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/leagues': typeof LeaguesIndexRoute
  '/api/public/cron/resolve-bets': typeof ApiPublicCronResolveBetsRoute
  '/api/public/cron/sync-matches': typeof ApiPublicCronSyncMatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bets': typeof BetsRoute
  '/profile': typeof ProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/api/public/cron/resolve-bets': typeof ApiPublicCronResolveBetsRoute
  '/api/public/cron/sync-matches': typeof ApiPublicCronSyncMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bets'
    | '/profile'
    | '/join/$code'
    | '/leagues/$leagueId'
    | '/leagues/'
    | '/api/public/cron/resolve-bets'
    | '/api/public/cron/sync-matches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bets'
    | '/profile'
    | '/join/$code'
    | '/leagues/$leagueId'
    | '/leagues'
    | '/api/public/cron/resolve-bets'
    | '/api/public/cron/sync-matches'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bets'
    | '/profile'
    | '/join/$code'
    | '/leagues/$leagueId'
    | '/leagues/'
    | '/api/public/cron/resolve-bets'
    | '/api/public/cron/sync-matches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BetsRoute: typeof BetsRoute
  ProfileRoute: typeof ProfileRoute
  JoinCodeRoute: typeof JoinCodeRoute
  LeaguesLeagueIdRoute: typeof LeaguesLeagueIdRoute
  LeaguesIndexRoute: typeof LeaguesIndexRoute
  ApiPublicCronResolveBetsRoute: typeof ApiPublicCronResolveBetsRoute
  ApiPublicCronSyncMatchesRoute: typeof ApiPublicCronSyncMatchesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bets': {
      id: '/bets'
      path: '/bets'
      fullPath: '/bets'
      preLoaderRoute: typeof BetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/': {
      id: '/leagues/'
      path: '/leagues'
      fullPath: '/leagues/'
      preLoaderRoute: typeof LeaguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$leagueId': {
      id: '/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof LeaguesLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-matches': {
      id: '/api/public/cron/sync-matches'
      path: '/api/public/cron/sync-matches'
      fullPath: '/api/public/cron/sync-matches'
      preLoaderRoute: typeof ApiPublicCronSyncMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/resolve-bets': {
      id: '/api/public/cron/resolve-bets'
      path: '/api/public/cron/resolve-bets'
      fullPath: '/api/public/cron/resolve-bets'
      preLoaderRoute: typeof ApiPublicCronResolveBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BetsRoute: BetsRoute,
  ProfileRoute: ProfileRoute,
  JoinCodeRoute: JoinCodeRoute,
  LeaguesLeagueIdRoute: LeaguesLeagueIdRoute,
  LeaguesIndexRoute: LeaguesIndexRoute,
  ApiPublicCronResolveBetsRoute: ApiPublicCronResolveBetsRoute,
  ApiPublicCronSyncMatchesRoute: ApiPublicCronSyncMatchesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
